version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "guinea*"
      - dependency-name: "amethystate*"
      - dependency-name: "ogurpchik*"
      - dependency-name: "uniproc-protocol"
      - dependency-name: "uniproc-agent-kit"
      - dependency-name: "guicons*"
      - dependency-name: "shown"
      - dependency-name: "windows-reactor*"
      - dependency-name: "windows-canvas*"
      - dependency-name: "windows"
      - dependency-name: "compio*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
    groups:
      cargo:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    groups:
      actions:
        patterns: ["*"]
