[package]
name = "uniproc-windows-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
windows-service = "0.8.0"
windows = { version = "0.62.2", features = [
    "Win32_System_Diagnostics_Etw", "Win32_System_Threading", "Win32_Foundation",
    "Win32_System_EventLog", "Win32_Security", "Win32_System_Registry",
    "Win32_System_Services", "Win32_System_Time", "Win32_System_SystemInformation",
    "Win32_System_Power", "Win32_System_Performance", "Wdk", "Wdk_System",
    "Wdk_Foundation", "Wdk_System_Threading", "Wdk_System_SystemInformation",
    "Win32_System_Diagnostics_Debug", "Win32_System_Kernel", "Win32_Storage_Packaging",
    "Win32_Storage_FileSystem",
    "Win32_Storage_Packaging_Appx", "Win32_UI", "Win32_UI_Shell",
    "Win32_Security_WinTrust", "Win32_Security_Cryptography",
    "Win32_Security_Cryptography_Catalog", "Win32_Security_Cryptography_Sip",
    "Win32_UI_WindowsAndMessaging"] }
ntapi = "0.4.3"
fxhash = "0.2.1"

ogurpchik = { git = "https://github.com/uniproc-dev/oguRPChik", tag = "v0.4.0" }
uniproc-protocol = { git = "https://github.com/uniproc-dev/uniproc-protocol", tag = "v0.4.0" }
capnp = "0.27"
capnp-rpc = "0.27"
dhat = "0.3.3"
clap = { version = "4", features = ["derive"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

chrono = { version = "0.4", features = ["clock"] }

anyhow = "1"
ctrlc = "3"
binrw = "0.15.0"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

parking_lot = "0.12"
crossbeam-channel = "0.5"

dashmap = "6.1.0"
compio = "0.18.0"
