[workspace]
members = ["crates/core", "crates/http", "crates/rpc", "crates/service"]
default-members = [".", "crates/core", "crates/http", "crates/rpc", "crates/service"]

[package]
name = "uniproc-windows-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
uniproc-windows-core = { path = "crates/core" }

windows = { git = "https://github.com/microsoft/windows-rs", rev = "c14074c45", features = [
    "winerror", "minwindef", "winnt", "windef", "handleapi", "errhandlingapi",
    "processthreadsapi", "winbase", "securitybaseapi", "winsvc"] }
ntapi = "0.4.3"

ogurpchik = { git = "https://github.com/uniproc-dev/oguRPChik", tag = "v0.6.3" }
uniproc-protocol = { git = "https://github.com/uniproc-dev/uniproc-protocol", tag = "v0.9.0" }
capnp = "0.27"
capnp-rpc = "0.27"

tracing = "0.1"
anyhow = "1"
parking_lot = "0.12"
crossbeam-channel = "0.5"

compio = { version = "0.18.0", features = ["time"] }
futures = "0.3"

[profile.profiling]
inherits = "release"
debug = true

[profile.release]
debug = true
