[package]
name = "uniproc-windows-rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
uniproc-windows-agent = { path = "../.." }

ogurpchik = { git = "https://github.com/uniproc-dev/oguRPChik", tag = "v0.6.3" }
uniproc-protocol = { git = "https://github.com/uniproc-dev/uniproc-protocol", tag = "v0.10.0" }
futures = "0.3"
capnp = "0.27"
capnp-rpc = "0.27"
compio = { version = "0.18.0", features = ["time"] }
anyhow = "1"
tracing = "0.1"
