[package]
name = "uniproc-windows-service"
version = "0.14.8"
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "uniproc-windows-agent"
path = "src/main.rs"

[features]
tracy = ["dep:tracing-tracy"]

[dependencies]
uniproc-windows-agent = { path = "../.." }
uniproc-windows-http = { path = "../http" }
uniproc-windows-rpc = { path = "../rpc" }

windows-service = "0.8.0"
clap = { version = "4", features = ["derive"] }
dhat = "0.3.3"
ctrlc = "3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tracy = { version = "0.12", default-features = false, features = ["enable", "only-localhost", "ondemand"], optional = true }
compio = { version = "0.18.0", features = ["time"] }
anyhow = "1"
