[package]
name = "uniproc-windows-core"
version = "0.21.0"
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
windows-core = "0.100"
ntapi = "0.4.3"
rustc-hash = "2"
binrw = "0.15.0"
amethystate = { version = "0.22", default-features = false, features = ["redb"] }
serde = { version = "1", features = ["derive", "rc"] }
anyhow = "1"
tracing = "0.1"
parking_lot = "0.12"
crossbeam-channel = "0.5"
enumset = "1.1"
uniproc-agent-kit = { git = "https://github.com/uniproc-dev/uniproc-agent-kit", tag = "v0.3.0" }
roxmltree = "0.20"
smol_str = { version = "0.3", features = ["serde"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
